build: include newly created efl_ui_focus_graph.h file in dist
This header file was newly created in 258b96be358e7313366ed9194360746ddcd3d6ea
Autotools need to made aware of it so it will actually land in the dist
or a distcheck run will break with:
../../../src/lib/elementary/efl_ui_focus_graph.c:9:10: fatal error: efl_ui_focus_graph.h: No such file or directory